server:
  port: ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: catalog
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**
        #- id: movies #endpoiunt privados
         # uri: lb://movies-service
          #predicates:
           # - Path=/movies/**              

info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

